from typing import TypedDict

from langgraph.graph import END, START, StateGraph

from app.llm.client import llm
from app.report.models import InvestmentReport


from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class ReportSectionId(str, Enum):
    """Identifiers for narrative sections in an investment report."""

    EXECUTIVE_SUMMARY = "executive_summary"
    COMPANY_OVERVIEW = "company_overview"
    FINANCIAL_SUMMARY = "financial_summary"
    MARKET_SUMMARY = "market_summary"
    INDUSTRY_MACRO_SUMMARY = "industry_macro_summary"
    VALUATION_SUMMARY = "valuation_summary"
    RISK_SUMMARY = "risk_summary"
    INVESTMENT_DECISION_SUMMARY = "investment_decision_summary"


EXPECTED_REPORT_SECTION_IDS = (
    ReportSectionId.EXECUTIVE_SUMMARY,
    ReportSectionId.COMPANY_OVERVIEW,
    ReportSectionId.FINANCIAL_SUMMARY,
    ReportSectionId.MARKET_SUMMARY,
    ReportSectionId.INDUSTRY_MACRO_SUMMARY,
    ReportSectionId.VALUATION_SUMMARY,
    ReportSectionId.RISK_SUMMARY,
    ReportSectionId.INVESTMENT_DECISION_SUMMARY,
)


REPORT_NARRATIVE_FIELD_MAP = {
    ReportSectionId.EXECUTIVE_SUMMARY: "executive_summary",
    ReportSectionId.COMPANY_OVERVIEW: "company_overview",
    ReportSectionId.FINANCIAL_SUMMARY: "financial_summary",
    ReportSectionId.MARKET_SUMMARY: "market_summary",
    ReportSectionId.INDUSTRY_MACRO_SUMMARY: "industry_macro_summary",
    ReportSectionId.VALUATION_SUMMARY: "valuation_summary",
    ReportSectionId.RISK_SUMMARY: "risk_summary",
    ReportSectionId.INVESTMENT_DECISION_SUMMARY: "investment_decision_summary",
}


class ReportSection(BaseModel):
    """A single LLM-generated narrative section."""

    model_config = ConfigDict(extra="forbid")

    section_id: ReportSectionId = Field(
        description="Identifier of the report section."
    )

    content: str = Field(
        min_length=1,
        description="Human-readable narrative content for the section.",
    )


class ReportNarrativeOutput(BaseModel):
    """Structured output boundary for LLM-generated report narrative."""

    model_config = ConfigDict(extra="forbid")

    sections: list[ReportSection] = Field(
        min_length=1,
        description="Narrative sections generated by the report LLM.",
    )


class ReportGenerationInputState(TypedDict):
    """Input contract for the report generation graph."""

    report: InvestmentReport


class ReportGenerationState(TypedDict, total=False):
    """Internal state used by the report generation graph."""

    report: InvestmentReport
    narrative: ReportNarrativeOutput | None
    generation_error: str | None
    merge_error: str | None


class ReportGenerationOutputState(TypedDict):
    """Output contract for the report generation graph."""

    report: InvestmentReport | None
    narrative: ReportNarrativeOutput | None
    generation_error: str | None
    merge_error: str | None


def validate_report_narrative(
    narrative: ReportNarrativeOutput,
) -> ReportNarrativeOutput:
    actual_section_ids = [section.section_id for section in narrative.sections]

    if len(actual_section_ids) != len(EXPECTED_REPORT_SECTION_IDS):
        raise ValueError(
            "Report narrative must contain exactly "
            f"{len(EXPECTED_REPORT_SECTION_IDS)} sections, "
            f"but received {len(actual_section_ids)}."
        )

    if len(set(actual_section_ids)) != len(actual_section_ids):
        raise ValueError(
            "Report narrative contains duplicate section IDs."
        )

    expected_section_ids = set(EXPECTED_REPORT_SECTION_IDS)
    actual_section_ids_set = set(actual_section_ids)

    missing_section_ids = expected_section_ids - actual_section_ids_set
    if missing_section_ids:
        raise ValueError(
            "Report narrative is missing required sections: "
            f"{sorted(section_id.value for section_id in missing_section_ids)}."
        )

    unexpected_section_ids = actual_section_ids_set - expected_section_ids
    if unexpected_section_ids:
        raise ValueError(
            "Report narrative contains unexpected sections: "
            f"{sorted(section_id.value for section_id in unexpected_section_ids)}."
        )

    if tuple(actual_section_ids) != EXPECTED_REPORT_SECTION_IDS:
        raise ValueError(
            "Report narrative sections are in an invalid order."
        )

    return narrative


def merge_report_narrative(
    report: InvestmentReport,
    narrative: ReportNarrativeOutput,
) -> InvestmentReport:
    validate_report_narrative(narrative)

    narrative_updates: dict[str, str] = {}

    for section in narrative.sections:
        field_name = REPORT_NARRATIVE_FIELD_MAP[section.section_id]
        narrative_updates[field_name] = section.content

    updated_data = report.model_dump()
    updated_data.update(narrative_updates)

    return InvestmentReport.model_validate(updated_data)


def merge_report_narrative_node(
    state: ReportGenerationState,
) -> ReportGenerationState:
    report = state.get("report")
    narrative = state.get("narrative")

    if report is None:
        return {
            "merge_error": "Report is required for narrative merge.",
        }

    if narrative is None:
        return {
            "merge_error": "Narrative is required for report merge.",
        }

    try:
        merged_report = merge_report_narrative(
            report,
            narrative,
        )

        return {
            "report": merged_report,
            "merge_error": None,
        }

    except Exception as exc:
        return {
            "merge_error": str(exc),
        }


def generate_report_narrative(
    state: ReportGenerationState,
) -> dict:
    """Generate human-readable report narrative from an InvestmentReport."""

    structured_report_llm = llm.with_structured_output(
        ReportNarrativeOutput
    )

    report = state["report"]

    prompt = f"""
You are an investment research report generation agent.

Your task is to transform the supplied structured investment analysis
into clear, professional, human-readable report narrative.

The supplied InvestmentReport and its nested domain objects are the
source of truth.

You must faithfully represent the supplied facts and conclusions.

You must NOT:
- perform new web searches;
- invent facts;
- invent financial data;
- perform a new valuation;
- change the current price;
- change the target price;
- change the expected upside;
- change the investment recommendation;
- change the investment horizon;
- change the conviction level;
- change the risk analysis;
- create new investment risks that are not supported by the input;
- create a new investment thesis;
- make a new investment decision.

You are responsible only for narrative generation.

The output must contain exactly one narrative section for each of
the following section identifiers:

1. executive_summary
2. company_overview
3. financial_summary
4. market_summary
5. industry_macro_summary
6. valuation_summary
7. risk_summary
8. investment_decision_summary

Each section must contain clear, concise, professional prose
appropriate for an investment research report.

InvestmentReport:

{report.model_dump_json(indent=2)}

Narrative generation requirements:

1. Preserve all important numerical facts from the supplied analysis.
2. Preserve the supplied valuation conclusion.
3. Preserve the supplied risk conclusions.
4. Preserve the supplied investment recommendation.
5. Preserve the supplied investment horizon and conviction.
6. Explain the analysis in natural language rather than merely
   repeating raw JSON.
7. Do not introduce unsupported claims.
8. Do not output Markdown headings.
9. Return only the structured narrative sections required by the schema.
"""

    try:
        narrative = structured_report_llm.invoke(prompt)

        narrative = validate_report_narrative(narrative)

        return {
            "narrative": narrative,
            "generation_error": None,
        }

    except Exception as exc:
        return {
            "narrative": None,
            "generation_error": str(exc),
        }

def route_after_generation(
    state: ReportGenerationState,
) -> str:
    if state.get("generation_error"):
        return "end"

    return "merge"

def build_report_generation_graph():
    graph = StateGraph(
        ReportGenerationState,
        input_schema=ReportGenerationInputState,
        output_schema=ReportGenerationOutputState,
    )

    graph.add_node(
        "generate_report_narrative",
        generate_report_narrative,
    )

    graph.add_node(
        "merge_report_narrative",
        merge_report_narrative_node,
    )

    graph.add_edge(
        START,
        "generate_report_narrative",
    )

    graph.add_conditional_edges(
        "generate_report_narrative",
        route_after_generation,
        {
            "merge": "merge_report_narrative",
            "end": END,
        },
    )

    graph.add_edge(
        "merge_report_narrative",
        END,
    )

    return graph.compile()


report_generation_graph = build_report_generation_graph()